# Generated by Django 3.1.4 on 2020-12-08 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Numeral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardinal_number', models.CharField(max_length=200)),
                ('ordinal_number', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infinitive', models.CharField(max_length=200)),
                ('past_tense', models.CharField(max_length=200)),
                ('past_participle', models.CharField(max_length=200)),
                ('translation', models.CharField(max_length=200)),
            ],
        ),
    ]
